# Generated by cucumber-sinatra. (2011-05-30 13:32:01 +0200)

ENV['RACK_ENV'] = 'test'

require 'bundler/setup'
Bundler.require :default, ENV['RACK_ENV']

require File.join(File.dirname(__FILE__), '..', '..', 'app/server.rb')

#require 'capybara'
require 'capybara/cucumber'
require 'test/unit/capybara'
#require 'rspec''


Capybara.run_server = false
Capybara.default_driver = :webkit
Capybara.app_host = 'http://localhost:3000'
Capybara.save_and_open_page_path = 'tmp'

class Mana::ServerWorld
  include Capybara
  include MiniTest::Assertions
end

World do
  Mana::ServerWorld.new
end
