source :rubygems

gem 'activesupport', :require => 'active_support'

gem 'em-websocket'
gem 'em-synchrony'
gem "mongoid", ">= 2.0.1"
gem 'bson_ext', '~> 1.4.0'

# gem 'require_all'

group :development do
  gem 'awesome_print'
  gem 'ruby-debug-base19'
  gem 'ruby-debug19'
  gem 'pry'
  gem 'pry-doc'
  gem 'guard-livereload'
end

group :tools do
  gem 'capistrano'
  gem 'capistrano_colors'
end
