# config/cucumber.yml
##YAML Template
<% opts = '--require features --format pretty --guess features' %>
---
default: <%= opts %>
autotest: <%= opts %> --color
autotest-all: <%= opts %> --color
debug: --format debug