default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: localhost
  port: 5432
  database: mana_development
  username: postgres
  password: toor

test:
  <<: *default
  host: localhost
  port: 5432
  database: mana_test
  username: postgres
  password: toor
