development:
  host: localhost
  port: 27017
#  database: mana_development
  database: mana_production
#  database: mana_development_master
#  identity_map_enabled: true

test:
  host: localhost
  database: mana_test

# set these environment variables on your prod server
production:
  host: localhost
  database: mana_production
  # host: <%= ENV['MONGOID_HOST'] %>
  # port: <%= ENV['MONGOID_PORT'] %>
  # username: <%= ENV['MONGOID_USERNAME'] %>
  # password: <%= ENV['MONGOID_PASSWORD'] %>
  # database: <%= ENV['MONGOID_DATABASE'] %>