address: 83.167.232.160
pid: pids/thin.pid
# log: og/thin.log
timeout: 30
port: 80
max_conns: 256
# chdir: /root/mana_production/current
# rackup: /root/mana_production/current/config/config.ru
rackup: config/config.ru
max_persistent_conns: 128
environment: production
servers: 1