address: 83.167.232.160
pid: /root/mana_production/shared/pids/thin.pid
log: /root/mana_production/shared/log/thin.log
timeout: 30
port: 80
max_conns: 1024
chdir: /root/mana_production/current
rackup: /root/mana_production/current/config/config.ru
max_persistent_conns: 512
environment: production
servers: 1