address: "ec2-176-34-195-147.eu-west-1.compute.amazonaws.com"
pid: pids/thin.pid
log: log/thin.log
timeout: 30
port: 8080
max_conns: 256
rackup: config.ru
max_persistent_conns: 128
environment: production
servers: 1